# Travis-CI Build for reedb
# see travis-ci.org for details

language: c

# Use the faster container-based infrastructure.
sudo: false
matrix:
  include:
    - compiler: gcc
      os: linux
      env: CONFIG=cmake

# Run the Build script
script:
  - ./travis.sh cmake

# Install required packages
addons:
  apt:
    packages:
      - libgcrypt-dev
      - libmicrohttpd-dev

  coverity_scan:
    project:
      name: "reepass/reedb"
      description: "Fully encrypted document-oriented database"
    notification_email: sabel.katharina@gmail.com
    build_command_prepend: cmake ..
    build_command: cmake --build .
    branch_pattern: coverity_scan
