# Travis-CI Build for reedb
# see travis-ci.org for details

language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "V+EsSa4JAI1mp5WjLMdc1jH9eO4HsfgLsZMdwy117ZW6EY9/jVySIHGBcZlatIvgucUkjhreFjofupn28reVtFR9teGsynt9mbFRszPvyLLydJ3kV5cM58xbRwxUhjzeVq6Q3BvcTZyG2knOSdUdQFwAXlNaNq65bQD/uLwur24="

# Use the faster container-based infrastructure.
sudo: false
matrix:
  include:
    - compiler: gcc
      os: linux
      env: CONFIG=cmake

# Run the Build script
script:
  - ./travis.sh cmake

# Install required packages
addons:
  apt:
    packages:
      - libgcrypt-dev
      - libmicrohttpd-dev

  coverity_scan:
    project:
      name: "reepass/reedb"
      description: "Fully encrypted document-oriented database"
    notification_email: sabel.katharina@gmail.com
    build_command_prepend: cmake ..
    build_command: cmake --build .
    branch_pattern: coverity_scan
