#############################
#                           #
#  Reedb travis build file  #
#                           #
#############################

language: cpp
compiler: g++
sudo: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "X6Vs5IfJBseYJoirGHQIigEbYE6k8gdl9fCP9SyW+ErDACFRCusWjHMkUjVEmfbcqaUtBetQcsKZip7twHNCgxvxzydXOa30jn4tzBkkVIcUgSw5Zd3nruUy6D3pdNuf0/5YhZYH2nL9slU81kgApqD9kg2o/Fkw27mqdNAk/6g="

compiler:
  - gcc
  - clang

before_install:
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - $CC --version
  - $CXX --version

# Run the Build script
script:
  - ./travis.sh

# Install required packages
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libgcrypt-dev       # C crypto - secure RAM
      - libcryptopp-dev     # C++ crypto - ciphers & keygen
      - libmicrohttpd-dev   # Micro C HTTP server

# This is turning into a huge cluster fuck
  coverity_scan:
    project:
      name: "reepass/reedb"
      description: "Fully encrypted document-oriented database"
    notification_email: sabel.katharina@gmail.com
    build_command_prepend: "./get_cmake.sh && mkdir _build && cd _build && ../../my_cmake/bin/cmake .."
    build_command: "../../my_cmake/bin/cmake --build ."
    branch_pattern: develop