#############################
#                           #
#  Reedb travis build file  #
#                           #
#############################

os: linux
dist: trusty
sudo: required
services: docker
language: c++

# Stop spamming me please...
notifications:
  email: false

env:
  global:
   - secure: "X6Vs5IfJBseYJoirGHQIigEbYE6k8gdl9fCP9SyW+ErDACFRCusWjHMkUjVEmfbcqaUtBetQcsKZip7twHNCgxvxzydXOa30jn4tzBkkVIcUgSw5Zd3nruUy6D3pdNuf0/5YhZYH2nL9slU81kgApqD9kg2o/Fkw27mqdNAk/6g="

services:
  - docker

before_install:
  - docker pull spacekookie/reedb-docker
  - docker run spacekookie/reedb-docker /bin/bash -c "pacman --noconfirm -Sy git; git clone https://github.com/reepass/libreedb/ -b develop ; mkdir libreedb/build ; cd libreedb/build ; cmake .. ; cmake --build ."

# This is turning into a huge cluster fuck
  coverity_scan:
    project:
      name: "reepass/reedb"
      description: "Fully encrypted document-oriented database"
    notification_email: sabel.katharina@gmail.com
    build_command_prepend: "./get_cmake.sh && ./prep_env.sh && mkdir _build && cd _build && ../../my_cmake/bin/cmake .."
    build_command: "../../my_cmake/bin/cmake --build ."
    branch_pattern: develop